LetsChat/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('chatApp.urls',namespace='chat')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chatApp/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('',views.HomePage.as_view(),name='homePage'),
    path('createroom/',views.CreateRoom.as_view(),name='createRoom'),
    path('room/<str:slug>/',views.RoomChat.as_view(),name='room'),
    path('joinroom/',views.JoinRoom.as_view(),name='joinRoom'),
    path('chat/',views.ChatPage.as_view(),name='chatPage'),
    path('signin/',views.LoginPage.as_view(),name='signin'),
    path('signout/',views.LogoutView.as_view(),name='signout'),
    path('signup/',views.RegisterPage.as_view(),name='signup'),

]

chatApp/models.py
from django.db import models
# from django.contrib.auth.models import User


class Room(models.Model):
    roomName = models.CharField(max_length=150,unique=True,null=False,blank=False)
    slug = models.CharField(max_length=100)
    def __str__(self):
        return self.roomName

chatApp/views.py
from django.shortcuts import redirect
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView,LogoutView
from django.views.generic import CreateView
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView
from .models import Room

class HomePage(LoginRequiredMixin,TemplateView):
    template_name = 'index.html'


class ChatPage(LoginRequiredMixin,TemplateView):
    template_name = 'chat.html'


class CreateRoom(TemplateView):
    template_name = 'createRoom.html'


class JoinRoom(TemplateView):
    template_name = 'joinRoom.html'

    def get_context_data(self, **kwargs):
        context = super(JoinRoom, self).get_context_data(**kwargs)
        context['data'] = Room.objects.all()
        return context
  

class RoomChat(DetailView):
    template_name = 'room.html'
    model = Room
    context_object_name = 'room'
    



#below is the views for the login, register and logout view.

class LoginPage(LoginView):
    template_name = 'signin.html'
    
    def post(self, request, *args, **kwargs):
        email = self.request.POST['email']
        password = self.request.POST['password']
        user = authenticate(request,username=email,password=password)
        if user is not None:
            login(request,user)
            messages.success(request,'you have logged into your account')
            return redirect('chat:homePage')
        else:
            messages.error(request,'cant login, check username or password')
            return redirect('chat:signin')

class RegisterPage(CreateView):
    template_name = 'signup.html'
    form_class = UserCreationForm

    def post(self, request, *args, **kwargs):
        email = self.request.POST['email']
        firstName = self.request.POST['firstname']
        lastName = self.request.POST['lastname']
        password = self.request.POST['password']
        passwordConf = self.request.POST['passwordConf']
        if password != passwordConf:
            messages.error(request, 'password do not match')
            return redirect('chat:register')
        else:
            user = User.objects.create_user(username=email,email=email,first_name = firstName, last_name = lastName, password = password)
            user.save()
            messages.success(request, 'your account has been created successfully')
            return redirect('chat:signin')

class LogoutView(LogoutView):
    next_page = 'chat:signin'

    def dispatch(self, request, *args, **kwargs):
        messages.info(request, "You have successfully logged out.")
        return super(LogoutView, self).dispatch(request, *args, **kwargs)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}letsChat</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/chatCss.css' %}">
    
</head>
<body>
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <!-- Container wrapper -->
    <div class="container">
      <!-- Navbar brand -->
      <a class="navbar-brand me-2" href="{% url 'chat:homePage' %}">Lets<span style="color: blue;">chat </span><i class="bi bi-chat"></i></a>
  
      <!-- Toggle button -->
      <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarButtonsExample"
        aria-controls="navbarButtonsExample"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarButtonsExample">
      {% if user.is_authenticated %}
         <!-- Left links -->
         <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'chat:homePage' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'chat:createRoom' %}">Create room</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'chat:joinRoom' %}">Join room</a>
          </li>
        </ul>
        <div class="d-flex align-items-center">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link">welcome {{request.user.first_name}}</a>
            </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'chat:signout' %}">sign out</a>
              </li>
          </ul>
      </div>  
        <!-- Left links -->
      {% else %}
      <div class="d-flex align-items-center">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'chat:signin' %}">sign in</a>
            </li>
            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'chat:signup' %}">sign up</a>
              </li>
        </ul>
    </div>
      {% endif %}

      <!-- Collapsible wrapper -->
      
       
  
        
      </div>
      <!-- Collapsible wrapper -->
    </div>
    <!-- Container wrapper -->
  </nav>
  <!-- Navbar -->

  {% block body %}
    
  {% endblock %}


  {% block script %}
    
  {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

templates/chat.html
{% extends 'base.html' %}


{% block title %}
    chat
{% endblock %}

{% block body %}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
          <div class="col-md-6">
            <div class="card card-bordered">
              <div class="card-header">
                <h4 class="card-title"><strong>Chat</strong></h4>
                <a class="btn btn-xs btn-secondary" href="#" data-abc="true">Let's Chat App</a>
              </div>


              <div class="ps-container ps-theme-default ps-active-y" id="chat-content" style="overflow-y: scroll !important; height:400px !important;">
                <div class="media media-chat">
                  <img class="avatar" src="https://img.icons8.com/color/36/000000/administrator-male.png" alt="...">
                  <div class="media-body">
                    <p>Hi</p>
                    <p>How are you ...???</p>
                    <p>What are you doing tomorrow?<br> Can we come up a bar?</p>
                    <p class="meta"><time datetime="2018">23:58</time></p>
                  </div>
                </div>

                <div class="media media-meta-day">Today</div>

                <div class="media media-chat media-chat-reverse">
                  <div class="media-body">
                    <p>Hiii, I'm good.</p>
                    <p>How are you doing?</p>
                    <p>Long time no see! Tomorrow office. will be free on sunday.</p>
                    <p class="meta"><time datetime="2018">00:06</time></p>
                  </div>
                </div>

                <div class="media media-chat">
                  <img class="avatar" src="https://img.icons8.com/color/36/000000/administrator-male.png" alt="...">
                  <div class="media-body">
                    <p>Okay</p>
                    <p>We will go on sunday? </p>
                    <p class="meta"><time datetime="2018">00:07</time></p>
                  </div>
                </div>

                <div class="media media-chat media-chat-reverse">
                  <div class="media-body">
                    <p>That's awesome!</p>
                    <p>I will meet you Sandon Square sharp at 10 AM</p>
                    <p>Is that okay?</p>
                    <p class="meta"><time datetime="2018">00:09</time></p>
                  </div>
                </div>

                <div class="media media-chat">
                  <img class="avatar" src="https://img.icons8.com/color/36/000000/administrator-male.png" alt="...">
                  <div class="media-body">
                    <p>Okay i will meet you on Sandon Square </p>
                    <p class="meta"><time datetime="2018">00:10</time></p>
                  </div>
                </div>

                <div class="media media-chat media-chat-reverse">
                  <div class="media-body">
                    <p>Do you have pictures of Matley Marriage?</p>
                    <p class="meta"><time datetime="2018">00:10</time></p>
                  </div>
                </div>

                <div class="media media-chat">
                  <img class="avatar" src="https://img.icons8.com/color/36/000000/administrator-male.png" alt="...">
                  <div class="media-body">
                    <p>Sorry I don't have. i changed my phone.</p>
                    <p class="meta"><time datetime="2018">00:12</time></p>
                  </div>
                </div>

                <div class="media media-chat media-chat-reverse">
                  <div class="media-body">
                    <p>Okay then see you on sunday!!</p>
                    <p class="meta"><time datetime="2018">00:12</time></p>
                  </div>
                </div>

              <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 0px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; height: 0px; right: 2px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 2px;"></div></div></div>

              <div class="publisher bt-1 border-light">
                <img class="avatar avatar-xs" src="https://img.icons8.com/color/36/000000/administrator-male.png" alt="...">
                <input class="publisher-input" type="text" placeholder="Write something">
                <span class="publisher-btn file-group">
                  <i class="fa fa-paperclip file-browser"></i>
                  <input type="file">
                </span>
                <a class="publisher-btn" href="#" data-abc="true"><i class="fa fa-smile"></i></a>
                <a class="publisher-btn text-info" href="#" data-abc="true"><i class="fa fa-paper-plane"></i></a>
              </div>

             </div>
          </div>
          </div>
          </div>
          </div>
{% endblock %}

templates/createRoom.html
{% extends 'base.html' %}

{% block body%}

<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-md-6">

	<h1>Create a chat room here</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" type="text" placeholder="Enter room name">
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}
    home
{% endblock %}

{% block body %}
    hello world 
{% endblock %}

templates/joinRoom.html
{% extends 'base.html' %}

{% block body %}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-md-6">
                <h1>Join a room and talk to like minds</h1>

                <div class="row">
                    {% for room in data %}
                        <div class="col-md-6">
                            <div class="card text-center">
                                <div class="card-body">
                                    <h5 class="card-title">{{room.roomName}}</h5>
                                    <a href="{% url 'chat:room' room.slug %}" class="btn btn-primary">join room</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    
            
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/room.html
{% extends 'base.html' %}

{% block body %}
    <div class="text-center">
        <h1 class="text-black">{{room.roomName}}</h1>
    </div>

    <div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
          <div class="col-md-6">
            <div class="card card-bordered">
              <div class="card-header">
              
                <div class="media media-chat">
                  <div class="media-body">
                    <p>Hi</p><span>sent by okon</span>

                    <p>How are you ...???</p><span>sent by okon</span>
                  </div>
                  <br>
                  <!-- <form action="">
                    <input class="publisher-input" type="text" placeholder="Write something">
                    <button class="btn btn-primary mb-3" type="submit">send</button>
                  </form> -->
                  <form class="row g-3">
                    <div class="col-auto">
                        <input class="publisher-input" type="text" placeholder="Write something">
                        <button class="btn btn-primary mb-3" type="submit">send</button>
                    </div>
                  </form>
                </div>
                
             </div>
          </div>
          </div>
          </div>
          </div>
{% endblock %}

{% block script %}
          {{ room.slug|json_script:'json-roomname' }}
          <script>
            const roomName = JSON.parse(document.getElementById('json-roomname').textContent);
            
            const chatSocket = new WebSocket(
              'ws://'
              + window.location.host
              + '/ws/'
              + roomName
              + '/'
            );


            chatSocket.onmessage = function(e){
              console.log('onmessage')
            }

            chatSocket.onclose = function(e){
              console.log('onclose')
            } 
          </script>
{% endblock %}

templates/signin.html
{% extends 'base.html' %}

{% block title %}
    sign in
{% endblock %}

{% block body %}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-md-6">
                
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input type="email" class="form-control" id="inputEmail" name="email" placeholder="Email">
                </div>
                <br>
                <div class="form-group">
                    <input type="password" class="form-control" id="inputPassword" name="password" placeholder="Password">
                </div>
                <br>
                <button type="submit" class="btn btn-primary">Sign in</button>
                <span style="padding-left:90px"><a style="text-decoration: none; color:black" href="{% url 'chat:signup' %}">i dont have an account</a> </span>
            </form>
                
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}
    sign up
{% endblock %}

{% block body %}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-md-6">
                
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input type="email" class="form-control" id="inputEmail" name="email" placeholder="Email">
                </div>
                <br>
                <div class="form-group">
                    <input type="text" class="form-control" id="inputEmail" name="firstname" placeholder="First name">
                </div>
                <br>
                <div class="form-group">
                    <input type="text" class="form-control" id="inputEmail" name="lastname" placeholder="Last name">
                </div>
                <br>
                <div class="form-group">
                    <input type="password" class="form-control" id="inputPassword" name="password" placeholder="Password">
                </div>
                <br>
                <div class="form-group">
                    <input type="password" class="form-control" id="inputPassword" name="passwordConf" placeholder="Confirm password">
                </div>
                <br>
                <button type="submit" class="btn btn-primary">Sign up</button>
                <span style="padding-left:90px"><a style="text-decoration: none; color:black" href="{% url 'chat:signin' %}">already have an account</a> </span>
            </form>
                
            </div>
        </div>
    </div>
</div>
{% endblock %}